### ISSUE TITLE
Test folder doesn't contain test_helper and application_system_test_case

### ISSUE THREAD

**Issue by nevware** [ralixjs/rails-ralix-tailwind#17]
Follow instructions - clone repo, run setup, run dev. Generate new models. Test folder contains tests for models, but when running rails test, it fails as there is no test_helper.rb in /test.

**Comment by markets** [comment]
Hey @nevware! Thanks for trying our template 🤝 

We are not currently providing testing setup, you're right! It was done this way on purpose, as it's quite easy to setup your preferred stack (Minitest vs RSpec). But maybe it would be more useful to provide some minimal/initial configuration using Rails defaults (via Minitest)?

**Comment by markets** [comment]
Thanks @nevware! Feel free to send a proposal to improve the documentation.

I'm gonna close this one, as we're not interested to provide a default "testing" setup right now.
