### ISSUE TITLE
why tailwind overrides other css in a rails app

### ISSUE THREAD

**Issue by godfreymutebi** [ralixjs/rails-ralix-tailwind#20]
I had a rails app which i initialized with --css  tailwind , but when i added action text , it seems that the CSS is being broken or overridden. Any idea on how i can solve this issue

**Comment by markets** [comment]
I think you should ask this in Stackoverflow, Reddit or the Rails repo. This repo is only a Rails template to quickly start your new Rails project with some batteries included. In fact, it contains Tailwind and ActionText too already configured.
